# Generated by Django 5.1.2 on 2024-10-25 16:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_guest",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_hotelmanager",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_receptionist",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="name",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="date_joined",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_superuser",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
