# Generated by Django 5.1.2 on 2024-10-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_customuser_is_guest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="_id",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterModelTable(
            name="customuser",
            table="custom_user",
        ),
    ]
