# Generated by Django 5.1.2 on 2024-10-25 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "field_id",
                    models.CharField(
                        db_column="_id",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("country", models.TextField(blank=True, null=True)),
                ("city", models.TextField(blank=True, null=True)),
                ("district", models.TextField(blank=True, null=True)),
                ("street", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("avg_rating", models.FloatField(blank=True, null=True)),
                ("min_price", models.FloatField(blank=True, null=True)),
                ("max_price", models.FloatField(blank=True, null=True)),
                ("num_rating", models.IntegerField(blank=True, null=True)),
                ("type", models.TextField(blank=True, null=True)),
                ("img", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "hotel",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HotelServices",
            fields=[
                ("name", models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "hotel_services",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "room_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RoomTypeServices",
            fields=[
                ("name", models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "room_type_services",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "hotel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="hotel.hotel",
                    ),
                ),
                ("no", models.IntegerField()),
                ("size", models.FloatField(blank=True, null=True)),
                ("avg_rating", models.FloatField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=10, null=True)),
                ("img", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "room",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HotelHasServices",
            fields=[
                (
                    "service_name",
                    models.OneToOneField(
                        db_column="service_name",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="hotel.hotelservices",
                    ),
                ),
            ],
            options={
                "db_table": "hotel_has_services",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RoomTypeHasServices",
            fields=[
                (
                    "service_name",
                    models.OneToOneField(
                        db_column="service_name",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="hotel.roomtypeservices",
                    ),
                ),
            ],
            options={
                "db_table": "room_type_has_services",
                "managed": False,
            },
        ),
    ]
