# Generated by Django 5.1.3 on 2024-12-06 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('field_id', models.CharField(db_column='_id', max_length=50, primary_key=True, serialize=False)),
                ('guest_id', models.CharField(max_length=50)),
                ('hotel_id', models.CharField(max_length=50)),
                ('is_repeated_guest', models.BooleanField(blank=True, null=True)),
                ('distribution_channel', models.TextField(blank=True, null=True)),
                ('reservation_status', models.TextField()),
                ('reservation_status_date', models.DateTimeField(blank=True, null=True)),
                ('total_of_special_requests', models.IntegerField(blank=True, null=True)),
                ('days_in_waiting_list', models.IntegerField(blank=True, null=True)),
                ('booking_date', models.DateTimeField()),
                ('check_in', models.DateField()),
                ('check_out', models.DateField(blank=True, null=True)),
                ('stays_day', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookingHasRoom',
            fields=[
                ('booking_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hotel_id', models.CharField(db_column='hotel_id', max_length=50)),
                ('room_no', models.IntegerField(db_column='room_no')),
                ('meal', models.CharField(blank=True, max_length=10, null=True)),
                ('parking_spaces', models.IntegerField(blank=True, null=True)),
                ('adults', models.IntegerField(blank=True, null=True)),
                ('children', models.IntegerField(blank=True, null=True)),
                ('babies', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'booking_has_room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('field_id', models.CharField(db_column='_id', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('street', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('avg_rating', models.FloatField(blank=True, null=True)),
                ('min_price', models.FloatField(blank=True, null=True)),
                ('max_price', models.FloatField(blank=True, null=True)),
                ('num_rating', models.IntegerField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('img', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hotel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HotelServices',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'hotel_services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('field_id', models.CharField(db_column='_id', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('password', models.CharField(max_length=50)),
                ('avatar', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('field_id', models.CharField(db_column='_id', max_length=50, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('original_amount', models.FloatField()),
                ('credit_card', models.TextField(blank=True, null=True)),
                ('deposit_type', models.TextField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'room_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomTypeHasServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'room_type_has_services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomTypeServices',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'room_type_service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionMethod',
            fields=[
                ('method', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'transaction_method',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HotelHasRoomType',
            fields=[
                ('hotel_id', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.hotel')),
                ('room_type', models.CharField(max_length=50, verbose_name='RoomType')),
                ('avg_rating', models.FloatField(blank=True, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('max_vacant', models.PositiveIntegerField(blank=True, null=True)),
                ('vacant', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hotel_has_room_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.hotel')),
                ('room_no', models.IntegerField(db_column='no')),
                ('size', models.FloatField(blank=True, null=True)),
                ('avg_rating', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('img', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HotelHasServices',
            fields=[
                ('service_name', models.OneToOneField(db_column='service_name', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.hotelservices')),
            ],
            options={
                'db_table': 'hotel_has_services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HotelManager',
            fields=[
                ('user', models.OneToOneField(db_column='_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.user')),
                ('hotel_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'hotel_manager',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('user', models.OneToOneField(db_column='_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.user')),
                ('hotel_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'receptionist',
                'managed': False,
            },
        ),
    ]
