# Generated by Django 5.1.3 on 2024-12-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelManager',
            fields=[
                ('field_id', models.CharField(db_column='_id', max_length=50, primary_key=True, serialize=False)),
                ('hotel_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'hotel_manager',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('field_id', models.CharField(db_column='_id', max_length=50, primary_key=True, serialize=False)),
                ('hotel_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'receptionist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('field_id', models.CharField(db_column='_id', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('password', models.CharField(max_length=50)),
                ('avatar', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
